apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: docker-kubernetes-load-balancer-frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 4200
          env:
            - name: BACKEND_API_URL
              value: "http://backend:8000"
